name: Build and save Docker image artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --tag spacedelivery:latest

      - name: Save image to a tar file
        run: docker save spacedelivery:latest -o ${{ runner.temp }}/spacedelivery.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-artifact
          path: ${{ runner.temp }}/spacedelivery.tar